### ISSUE TITLE
Surv(tstart, tstop, dd) : Invalid status value, converted to NA

### ISSUE THREAD

**Issue by funnell** [vdblab/FLORAL#17]
`xy$dd` is just some integers (multiple states) and `Surv` doesn't seem to like that

https://github.com/vdblab/FLORAL/blob/d10d714ed5362785452d422092cb5f6553fe2494/R/FLORAL.R#L213

**Comment by tengfei-emory** [comment]
I may have fixed this in the `dev` branch. Can you try it?

**Comment by funnell** [comment]
yes that seemed to fix it!
